name: Remove GunduzTech from All Projects

on:
  workflow_dispatch:  # Manuel çalıştırma için
  push:
    branches:
      - main  # Eğer GunduzTech güncellendiğinde otomatik çalıştırmak istersen

jobs:
  remove-gunduztech:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "frkngndz60@gmail.com"
          git config --global user.name "dgdfurkan"

      - name: Define Repository List
        id: define-repos
        run: |
          FINAL_REPOS="2048 77_Dream_Head_Soccer BattleWheelsMayhemArena Bilgi_Arcade_Idle Bilgi_Arcade_Idle_ Buildopolis Bus_Jam Claw-of-Vengeance FarmDynasty Flappy_Bird GamepatronDemo Guardian-Globe GunduzDev GunduzDevModule GunduzDevTemplate Linguistics-Root MathGame Picker3D Revolt_of_the_Exiles StackGame-Case Swim-n-Snack Tetris_GD UretkenAkademiCase VictoryDawn"
          echo "FINAL_REPOS=$FINAL_REPOS" >> $GITHUB_ENV

      - name: Remove GunduzTech from All Projects
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          IFS=' ' read -r -a REPO_ARRAY <<< "$FINAL_REPOS"
          
          for repo in "${REPO_ARRAY[@]}"; do
            if [[ -n "$repo" && "$repo" != " " ]]; then
              echo "Processing $repo..."
              
              git clone --depth=1 https://${GH_PAT}@github.com/dgdfurkan/$repo.git || continue
              cd $repo
              
              if [ -d "Assets/GunduzTech" ]; then
                git checkout main
                git pull origin main
              
                git rm -r --cached Assets/GunduzTech
                rm -rf Assets/GunduzTech
                git commit -m "Removed GunduzTech subtree from Assets" || echo "No changes to commit"
                git push origin main
              else
                echo "Skipping $repo, no Assets/GunduzTech found."
              fi
              
              cd ..
              rm -rf $repo
            fi
          done
